spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    userName: root
    password: 123456789
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_sell?characterEncoding=utf-8&useSSL=false
    jap:
      show-sql: true
